#version tag, should be always present at the beginning
version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file:
      - .env
    hostname: localhost #do i need this?
    networks:
      - inception
    ports:
      - 443:443 #pc-port:container-port to connect between pc and container
    volumes:
      - wordpress:/var/www

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/

volumes: 
  wordpress:
    name: wp-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  mariadb:
    name: mariadb-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge